member = User.create(username: "Member",
                    email: FFaker::Internet.email,
                    password: '123456',
                    password_confirmation: '123456')
member.add_role :member
admin = User.create(username: "Admin",
                    email: FFaker::Internet.email,
                    password: '123456',
                    password_confirmation: '123456')
admin.add_role :admin

members = []
members << member

(1..19).each do |n|
    new_member = User.create(username: "Member ##{n}",
                             email: FFaker::Internet.email,
                             password: '123456',
                             password_confirmation: '123456')
end

members.each do |member|
    attendances = []
    25.times do
        attendances << Attendance.new(date: Date.today - rand(100),
                                      user_id: member.id)
    end
    sorted_attendances = attendances.sort_by { |attendance| attendance.date }
    sorted_attendances.each do |attendance|
        attendance.save
    end
end

PhysicalTest.create(suggested_program: "AN",
                    user_id: 9,
                    created_at: "2019-02-14 20:49:03",
                    updated_at: "2019-04-15 20:53:49",
                    pull_ups: 10,
                    pull_ups_form: "Completa",
                    pull_ups_rom: "Ok",
                    pull_ups_core: "Involucra",
                    pull_ups_rhythm: "Continua",
                    pull_ups_notes: "",
                    push_ups: 10,
                    push_ups_form: "Completa",
                    push_ups_rom: "Ok",
                    push_ups_core: "Involucra",
                    push_ups_rhythm: "Intermitente",
                    push_ups_notes: "",
                    squats: 20,
                    squats_form: "Estabilidad rodillas",
                    squats_rom: "Ok",
                    squats_core: "Involucra",
                    squats_rhythm: "Continua",
                    squats_notes: "",
                    crunches: 18,
                    crunches_form: "Completa",
                    crunches_rom: "Ok",
                    crunches_core: "No apalanca",
                    crunches_rhythm: "Continua",
                    crunches_notes: "",
                    general_notes: "")

PhysicalTest.create(suggested_program: "AN",
                    user_id: 9,
                    created_at: "2019-03-06 20:49:41",
                    updated_at: "2019-04-15 20:54:34",
                    pull_ups: 15,
                    pull_ups_form: "Completa",
                    pull_ups_rom: "Ok",
                    pull_ups_core: "Involucra",
                    pull_ups_rhythm: "Continua",
                    pull_ups_notes: "",
                    push_ups: 21,
                    push_ups_form: "Completa",
                    push_ups_rom: "Ok",
                    push_ups_core: "Involucra",
                    push_ups_rhythm: "Continua",
                    push_ups_notes: "",
                    squats: 23,
                    squats_form: "Estabilidad rodillas",
                    squats_rom: "Ok",
                    squats_core: "Involucra",
                    squats_rhythm: "Continua",
                    squats_notes: "",
                    crunches: 26,
                    crunches_form: "Completa",
                    crunches_rom: "Otra",
                    crunches_core: "No apalanca",
                    crunches_rhythm: "Continua",
                    crunches_notes: "",
                    general_notes: "")

PhysicalTest.create(suggested_program: "AN",
                    user_id: 9,
                    created_at: "2019-03-26 20:55:34",
                    updated_at: "2019-04-15 20:55:58",
                    pull_ups: 24,
                    pull_ups_form: "Completa",
                    pull_ups_rom: "Ok",
                    pull_ups_core: "Involucra",
                    pull_ups_rhythm: "Continua",
                    pull_ups_notes: "",
                    push_ups: 32,
                    push_ups_form: "Completa",
                    push_ups_rom: "Ok",
                    push_ups_core: "No Involucra",
                    push_ups_rhythm: "Continua",
                    push_ups_notes: "",
                    squats: 26,
                    squats_form: "Estabilidad rodillas",
                    squats_rom: "Ok",
                    squats_core: "Involucra",
                    squats_rhythm: "Continua",
                    squats_notes: "",
                    crunches: 29,
                    crunches_form: "Completa",
                    crunches_rom: "Ok",
                    crunches_core: "No apalanca",
                    crunches_rhythm: "Continua",
                    crunches_notes: "",
                    general_notes: "")

PhysicalTest.create(suggested_program: "AN",
                    user_id: 9,
                    created_at: "2019-04-15 20:56:40",
                    updated_at: "2019-04-15 20:56:40",
                    pull_ups: 20,
                    pull_ups_form: "Completa",
                    pull_ups_rom: "Ok",
                    pull_ups_core: "Involucra",
                    pull_ups_rhythm: "Continua",
                    pull_ups_notes: "",
                    push_ups: 27,
                    push_ups_form: "Completa",
                    push_ups_rom: "Ok",
                    push_ups_core: "Involucra",
                    push_ups_rhythm: "Continua",
                    push_ups_notes: "",
                    squats: 16,
                    squats_form: "Estabilidad rodillas",
                    squats_rom: "Ok",
                    squats_core: "Involucra",
                    squats_rhythm: "Continua",
                    squats_notes: "",
                    crunches: 22,
                    crunches_form: "Completa",
                    crunches_rom: "Ok",
                    crunches_core: "No apalanca",
                    crunches_rhythm: "Continua",
                    crunches_notes: "",
                    general_notes: "")

PhysicalTest.create(suggested_program: "PR",
                    user_id: 12,
                    created_at: "2019-02-14 21:27:40",
                    updated_at: "2019-04-15 23:14:28",
                    pull_ups: 6,
                    pull_ups_form: "Completa",
                    pull_ups_rom: "Ok",
                    pull_ups_core: "Involucra",
                    pull_ups_rhythm: "Continua",
                    pull_ups_notes: "",
                    push_ups: 13,
                    push_ups_form: "Completa",
                    push_ups_rom: "Ok",
                    push_ups_core: "Involucra",
                    push_ups_rhythm: "Continua",
                    push_ups_notes: "",
                    squats: 15,
                    squats_form: "Estabilidad rodillas",
                    squats_rom: "Ok",
                    squats_core: "Involucra",
                    squats_rhythm: "Continua",
                    squats_notes: "",
                    crunches: 20,
                    crunches_form: "Asistida",
                    crunches_rom: "Ok",
                    crunches_core: "No apalanca",
                    crunches_rhythm: "Continua",
                    crunches_notes: "",
                    general_notes: "")

PhysicalTest.create(suggested_program: "PR",
                    user_id: 13,
                    created_at: "2019-03-06 21:27:40",
                    updated_at: "2019-04-15 23:14:41",
                    pull_ups: 16,
                    pull_ups_form: "Completa",
                    pull_ups_rom: "Ok",
                    pull_ups_core: "No Involucra",
                    pull_ups_rhythm: "Continua",
                    pull_ups_notes: "",
                    push_ups: 18,
                    push_ups_form: "Completa",
                    push_ups_rom: "Ok",
                    push_ups_core: "Involucra",
                    push_ups_rhythm: "Continua",
                    push_ups_notes: "",
                    squats: 15,
                    squats_form: "Estabilidad rodillas",
                    squats_rom: "Ok",
                    squats_core: "Involucra",
                    squats_rhythm: "Continua",
                    squats_notes: "",
                    crunches: 27,
                    crunches_form: "Completa",
                    crunches_rom: "Ok",
                    crunches_core: "No apalanca",
                    crunches_rhythm: "Continua",
                    crunches_notes: "",
                    general_notes: "")

PhysicalTest.create(suggested_program: "PR-Cardio",
                    user_id: 13,
                    created_at: "2019-03-26 21:27:40",
                    updated_at: "2019-04-15 23:15:31",
                    pull_ups: 19,
                    pull_ups_form: "Completa",
                    pull_ups_rom: "Ok",
                    pull_ups_core: "Involucra",
                    pull_ups_rhythm: "Continua",
                    pull_ups_notes: "",
                    push_ups: 21,
                    push_ups_form: "Completa",
                    push_ups_rom: "Ok",
                    push_ups_core: "Involucra",
                    push_ups_rhythm: "Continua",
                    push_ups_notes: "",
                    squats: 25,
                    squats_form: "Estabilidad rodillas",
                    squats_rom: "Ok",
                    squats_core: "Involucra",
                    squats_rhythm: "Continua",
                    squats_notes: "",
                    crunches: 27,
                    crunches_form: "Completa",
                    crunches_rom: "Ok",
                    crunches_core: "No apalanca",
                    crunches_rhythm: "Continua",
                    crunches_notes: "",
                    general_notes: "")

PhysicalTest.create(suggested_program: "PR",
                    user_id: 13,
                    created_at: "2019-04-15 23:10:09",
                    updated_at: "2019-04-15 23:10:09",
                    pull_ups: 19,
                    pull_ups_form: "Completa",
                    pull_ups_rom: "Ok",
                    pull_ups_core: "Involucra",
                    pull_ups_rhythm: "Continua",
                    pull_ups_notes: "",
                    push_ups: 15,
                    push_ups_form: "Completa",
                    push_ups_rom: "Ok",
                    push_ups_core: "Involucra",
                    push_ups_rhythm: "Continua",
                    push_ups_notes: "",
                    squats: 24,
                    squats_form: "Estabilidad rodillas",
                    squats_rom: "Ok",
                    squats_core: "Involucra",
                    squats_rhythm: "Continua",
                    squats_notes: "",
                    crunches: 32,
                    crunches_form: "Completa",
                    crunches_rom: "Ok",
                    crunches_core: "No apalanca",
                    crunches_rhythm: "Continua",
                    crunches_notes: "",
                    general_notes: "")

PhysicalTest.create(suggested_program: "PR-Cardio",
                    user_id: 12,
                    created_at: "2019-03-06 21:27:40",
                    updated_at: "2019-04-15 23:16:01",
                    pull_ups: 22,
                    pull_ups_form: "Completa",
                    pull_ups_rom: "Ok",
                    pull_ups_core: "Involucra",
                    pull_ups_rhythm: "Continua",
                    pull_ups_notes: "",
                    push_ups: 30,
                    push_ups_form: "Completa",
                    push_ups_rom: "Ok",
                    push_ups_core: "Involucra",
                    push_ups_rhythm: "Continua",
                    push_ups_notes: "",
                    squats: 29,
                    squats_form: "Estabilidad rodillas",
                    squats_rom: "Ok",
                    squats_core: "Involucra",
                    squats_rhythm: "Continua",
                    squats_notes: "",
                    crunches: 22,
                    crunches_form: "Completa",
                    crunches_rom: "Ok",
                    crunches_core: "No apalanca",
                    crunches_rhythm: "Continua",
                    crunches_notes: "",
                    general_notes: "")

PhysicalTest.create(suggested_program: "PR",
                    user_id: 12,
                    created_at: "2019-03-26 21:27:40",
                    updated_at: "2019-04-15 23:16:12",
                    pull_ups: 35,
                    pull_ups_form: "Completa",
                    pull_ups_rom: "Ok",
                    pull_ups_core: "Involucra",
                    pull_ups_rhythm: "Continua",
                    pull_ups_notes: "",
                    push_ups: 31,
                    push_ups_form: "Completa",
                    push_ups_rom: "Ok",
                    push_ups_core: "Involucra",
                    push_ups_rhythm: "Continua",
                    push_ups_notes: "",
                    squats: 28,
                    squats_form: "Estabilidad rodillas",
                    squats_rom: "Ok",
                    squats_core: "Involucra",
                    squats_rhythm: "Continua",
                    squats_notes: "",
                    crunches: 23,
                    crunches_form: "Completa",
                    crunches_rom: "Ok",
                    crunches_core: "No apalanca",
                    crunches_rhythm: "Continua",
                    crunches_notes: "",
                    general_notes: "")

PhysicalTest.create(suggested_program: "PR",
                    user_id: 14,
                    created_at: "2019-02-14 21:27:40",
                    updated_at: "2019-04-15 23:16:26",
                    pull_ups: 25,
                    pull_ups_form: "Completa",
                    pull_ups_rom: "Ok",
                    pull_ups_core: "Involucra",
                    pull_ups_rhythm: "Continua",
                    pull_ups_notes: "",
                    push_ups: 21,
                    push_ups_form: "Completa",
                    push_ups_rom: "Ok",
                    push_ups_core: "Involucra",
                    push_ups_rhythm: "Continua",
                    push_ups_notes: "",
                    squats: 23,
                    squats_form: "Estabilidad rodillas",
                    squats_rom: "Otra",
                    squats_core: "Involucra",
                    squats_rhythm: "Continua",
                    squats_notes: "",
                    crunches: 37,
                    crunches_form: "Completa",
                    crunches_rom: "Ok",
                    crunches_core: "No apalanca",
                    crunches_rhythm: "Continua",
                    crunches_notes: "",
                    general_notes: "")

PhysicalTest.create(suggested_program: "PR-Cardio",
                    user_id: 14,
                    created_at: "2019-04-15 23:20:02",
                    updated_at: "2019-04-15 23:20:02",
                    pull_ups: 16,
                    pull_ups_form: "Australiana",
                    pull_ups_rom: "Ok",
                    pull_ups_core: "Involucra",
                    pull_ups_rhythm: "Continua",
                    pull_ups_notes: "",
                    push_ups: 7,
                    push_ups_form: "Completa",
                    push_ups_rom: "Ok",
                    push_ups_core: "Involucra",
                    push_ups_rhythm: "Continua",
                    push_ups_notes: "",
                    squats: 9,
                    squats_form: "Estabilidad rodillas",
                    squats_rom: "Ok",
                    squats_core: "Involucra",
                    squats_rhythm: "Continua",
                    squats_notes: "",
                    crunches: 15,
                    crunches_form: "Completa",
                    crunches_rom: "Ok",
                    crunches_core: "No apalanca",
                    crunches_rhythm: "Continua",
                    crunches_notes: "",
                    general_notes: "")

